In [1]:
import sys
import numpy as np

##Arrays

In [2]:
a = np.array([1,2,3,4])
a.dtype

dtype('int64')

In [3]:
b = np.array([0,0.5,1,1.5,2])
b.dtype

dtype('float64')

In [4]:
a[0], a[1]

(np.int64(1), np.int64(2))

In [5]:
a[0:]

array([1, 2, 3, 4])

In [6]:
a[1:3]

array([2, 3])

In [7]:
a[::2]

array([1, 3])

In [8]:
b[0],b[1],b[2]

(np.float64(0.0), np.float64(0.5), np.float64(1.0))

In [9]:
b[[0,1,2]]

array([0. , 0.5, 1. ])

In [10]:
c = np.array([1,2,3,4], dtype=np.float64)
c.dtype

dtype('float64')

##Dimensions and Shapes

In [11]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [12]:
A.shape

(3, 3)

In [13]:
A.ndim

2

In [14]:
A.size

9

In [15]:
B = np.array([[
    [1,2,3],
    [4,5,6]
], [
    [10,11,12],
    [13,14,15]
]])

In [16]:
B.shape

(2, 2, 3)

In [17]:
B.ndim

3

In [18]:
B.size

12

##Indexing and Slicing of Matrices

In [19]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [20]:
A[0]

array([1, 2, 3])

In [21]:
A[0][0]

np.int64(1)

In [22]:
A[0, 0]

np.int64(1)

In [23]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
A[1:, 1:]

array([[5, 6],
       [8, 9]])

In [25]:
A[2] = 1

In [26]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

##Summary Statistics

In [27]:
a = np.array([1,2,3,4,5])

In [28]:
a.sum()

np.int64(15)

In [29]:
a.mean()

np.float64(3.0)

In [30]:
a.std()

np.float64(1.4142135623730951)

In [31]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [32]:
A.sum()

np.int64(45)

In [33]:
A.mean()

np.float64(5.0)

In [34]:
A.std()

np.float64(2.581988897471611)

In [35]:
A.sum(axis=0)

array([12, 15, 18])

In [36]:
A.sum(axis=1)

array([ 6, 15, 24])

##Broadcasting and Vectorized Operations

In [37]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [38]:
a + 10

array([10, 11, 12, 13])

In [39]:
print(a)

[0 1 2 3]


In [40]:
a += 10
print(a)

[10 11 12 13]


In [41]:
b = np.array([10,10,10,10])
a + b

array([20, 21, 22, 23])

##Boolean Arrays

In [42]:
  a = np.arange(4)
  print(a)

[0 1 2 3]


In [43]:
a[0], a[1]

(np.int64(0), np.int64(1))

In [44]:
a[[0,1]]

array([0, 1])

In [45]:
a[[True, False, False, True]]

array([0, 3])

In [46]:
a >= 2

array([False, False,  True,  True])

In [47]:
a[a >= 2]

array([2, 3])

In [48]:
a.mean()

np.float64(1.5)

In [49]:
A = np.random.randint(100, size=(3,3))
print(A)

[[31 24 46]
 [ 3 26 72]
 [29 15 38]]


In [50]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([31, 46, 26, 29, 38])

In [51]:
A[A > 30]

array([31, 46, 72, 38])

##Linear Algebra

In [52]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [53]:
B = np.array([
    [11,12,13],
    [14,15,16],
    [17,18,19]
])

In [54]:
A.dot(B)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [55]:
A @ B

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [56]:
B.T

array([[11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])

In [57]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
B.T @ A

array([[186, 228, 270],
       [198, 243, 288],
       [210, 258, 306]])

##Performance

In [59]:
l = list(range(100000))

In [60]:
nl = np.arange(100000)

In [61]:
%time sum([ x ** 2 for x in l ])

CPU times: user 13 ms, sys: 3.71 ms, total: 16.7 ms
Wall time: 36.3 ms


333328333350000

In [62]:
%time np.sum(nl ** 2)

CPU times: user 377 µs, sys: 54 µs, total: 431 µs
Wall time: 549 µs


np.int64(333328333350000)